---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Run Build
      command: npm run build:dev

- hosts: [suplay_dashboard_test]
  become: yes
  become_user: root
  become_method: sudo
  serial: 1
  tasks:
    - name: Copy build to remote directory
      copy:
        src: '../dist/'
        dest: '/usr/share/nginx/html/suplay-admin/'
        mode: '0755'
